---
title: "KI verstehen"
---

This presentation reveals why offloading cognitive processing to AI can undermine the development of genuine expertise. Through ACT-R [@andersonAdaptiveCharacterThought2013; @andersonHowCanHuman2007] theory, it explains how learning transforms declarative knowledge into procedural skills via productive struggle. The process involves grappling with confusion, making mistakes, and adjusting strategies—steps that are easily bypassed when using AI.

**The key takeaway:** Struggling, confusion and effort aren't obstacles to learning---they're the very mechanisms that
  build lasting expertise.



## {{< bi file-slides >}} Was ist Künstliche Intelligenz

{{< revealjs file="../slides/was-ist-ki/index.html" class="ratio ratio-16x9" >}}



## {{< bi file-slides >}} Wie funktionieren Chatbots?

{{< revealjs file="../slides/was-sind-chatbots/index.html" height="500px" class="ratio ratio-16x9" >}}


## {{< bi file-slides >}} Möglichkeiten und Grenzen

{{< revealjs file="../slides/möglichkeiten-grenzen/index.html" height="500px" class="ratio ratio-16x9" >}}

## {{< bi file-slides >}} Prompting Tipps

{{< revealjs file="../slides/prompting/index.html" height="500px" class="ratio ratio-16x9" >}}




## {{< bi book>}} Weiterführende Kurse

- [KI in der Lehre: Einsteiger](https://virtuelleakademie.github.io/ki-lehre-beginner/workshop/)
- [KI in der Lehre: Intermediate](https://virtuelleakademie.github.io/ki-lehre-intermediate/workshop/)
- [KI in der Lehre: Advanced](https://virtuelleakademie.github.io/ki-lehre-advanced/workshop/)
<!-- ## {{< bi file-slides >}} Bibliographie -->